version: '3.8'

services:
  flask-api:
    build: .
    container_name: flask-api-service
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  newman-tests:
    image: postman/newman:latest
    container_name: newman-runner
    volumes:
      - ./tests:/etc/newman
    depends_on:
      flask-api:
        condition: service_healthy
    command:
      run /etc/newman/postman_collection.json --env-var "baseUrl=http://flask-api:5000"