version: '3.8'

services:
  flask-api:
    build: .
    container_name: flask-api-service
    ports:
      - "5000:5000" 
    healthcheck:
      # Usamos 127.0.0.1 porque el comando corre DENTRO del contenedor
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s # Tiempo de gracia para que Flask inicie antes de fallar el check
    networks:
      - api-network

  newman-tests:
    image: postman/newman:latest
    container_name: newman-runner
    volumes:
      - ./tests:/etc/newman
      - ./newman-reports:/etc/newman-reports # Carpeta donde se guardará el reporte
    depends_on:
      flask-api:
        condition: service_healthy
    networks:
      - api-network
    # Instalamos el reportero y ejecutamos generando el archivo HTML
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        npm install -g newman-reporter-htmlextra
        newman run /etc/newman/postman_collection.json \
        --env-var "baseUrl=http://flask-api:5000" \
        --reporters cli,htmlextra \
        --reporter-htmlextra-export /etc/newman-reports/report.html

networks:
  api-network:
    driver: bridge